"""add container start time

Revision ID: 00789e0e53f4
Revises: f9b7f83e9767
Create Date: 2026-08-13 20:11:53.640355
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "00789e0e53f4"
down_revision: str | Sequence[str] | None = "f9b7f83e9767"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("docker_samples", schema=None) as batch_op:
        batch_op.add_column(sa.Column("started_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("docker_samples", schema=None) as batch_op:
        batch_op.drop_column("started_at")

    # ### end Alembic commands ###
