"""add uptime metric

Revision ID: 578f65485fb1
Revises: 7ad6eaa18741
Create Date: 2026-08-13 20:05:34.959284
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "578f65485fb1"
down_revision: str | Sequence[str] | None = "7ad6eaa18741"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("metric_samples", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uptime_seconds", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("metric_samples", schema=None) as batch_op:
        batch_op.drop_column("uptime_seconds")

    # ### end Alembic commands ###
