"""add disk hardware metadata

Revision ID: f9b7f83e9767
Revises: 578f65485fb1
Create Date: 2026-08-13 20:07:52.468677
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f9b7f83e9767"
down_revision: str | Sequence[str] | None = "578f65485fb1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("disk_samples", schema=None) as batch_op:
        batch_op.add_column(sa.Column("manufacturer", sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column("interface", sa.String(length=80), nullable=True))
    op.execute(
        "UPDATE disk_samples SET manufacturer = 'ServerSense Labs', interface = 'SATA' "
        "WHERE serial LIKE 'DEMO-%'"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("disk_samples", schema=None) as batch_op:
        batch_op.drop_column("interface")
        batch_op.drop_column("manufacturer")

    # ### end Alembic commands ###
